if: tag IS blank

language: node_js

node_js: 9

cache:
  directories:
    - node_modules

stages:
  - test
  - release

before_install: export PATH=$PATH:$TRAVIS_BUILD_DIR/.scripts

jobs:
  include:
    - stage: test

    - stage: release
      install: npm install --production
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
